
include:
- board: akdk_bt1
  shield: zion01_left
  snippet: studio-rpc-usb-uart
  cmake-args: >
    -DCONFIG_ZMK_STUDIO=y
    -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y   # ←★追加
  - board: akdk_bt1
    shield: zion01_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
