include:
  - board: akdk_bt1          # ┐ 左手：central にする
    shield: zion01_left      # │
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y   # 左手を central に指定

  - board: akdk_bt1          # ┐ 右手：peripheral のまま
    shield: zion01_right     # │
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y

  - board: akdk_bt1          # リセット用（必要ならそのまま）
    shield: settings_reset
